apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  elasticsearch.yml: |
    xpack.security.http.ssl.enabled: false
    xpack.security.enabled: true
    xpack.security.enrollment.enabled: true
    discovery.type: single-node
    network.host: 0.0.0.0
    http.port: 9200
    transport.port: 9300
    bootstrap.memory_lock: true
    cluster.name: "elasticsearch"
    node.name: "elasticsearch-node"
    path.data: /usr/share/elasticsearch/data
    path.logs: /usr/share/elasticsearch/logs